export const ACCOUNT_AUTH_STATUS_CHANGED = 'ACCOUNT_AUTH_STATUS_CHANGED';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
export const ACCOUNT_MENUS = 'ACCOUNT_MENUS';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const ADD_VISITED_VIEWS = 'ADD_VISITED_VIEWS';
export const DEL_VISITED_VIEWS = 'DEL_VISITED_VIEWS';
export const SET_ROUTERS = 'SET_ROUTERS';
export const BUTTON_PERMISSION = 'BUTTON_PERMISSION';